### ISSUE TITLE
The licence is not registered

### ISSUE THREAD

**Issue by oufmilo** [YunoHost-Apps/bookwyrm_ynh#10]
### Describe the bug

! manifest

    ! The license id 'ANTI-CAPITALIST SOFTWARE LICENSE (v 1.4)' is not registered in https://spdx.org/licenses/. 

I don't know how we can fix this.

**Comment by PrivacyDragon** [comment]
If that license really has to be registered, I do not think it can be fixed?
Otherwise, I have no idea either.
See this issue, they will not include the ACSL license: https://github.com/spdx/license-list-XML/issues/1228
