### ISSUE TITLE
Missing migrations in upgrade script

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/bookwyrm_ynh#17]
Thanks to all who have worked on this package! It’s a wonderful app :D 

I’ve just tried the upgrade to 0.5.4 from 0.5.3 (from master to testing branch). The upgrade worked well without error. But after, there was an error each time I tried to use Bookwyrm.

After `sudo -u bookwyrm /var/www/bookwyrm/venv/bin/python3 /var/www/bookwyrm/manage.py showmigrations`, a few missing migrations where showed.

So I tried `sudo -u bookwyrm /var/www/bookwyrm/venv/bin/python3 /var/www/bookwyrm/manage.py makemigrations` but this handled only one migration, so I `sudo -u bookwyrm /var/www/bookwyrm/venv/bin/python3 /var/www/bookwyrm/manage.py migrate` and all migrations were done. I can access Bookwyrm again and on version 0.5.4.

Last command did the job, but I don’t know if the `makemigrations `command was useful.

**Comment by panomaki** [comment]
Yes, this works (the last command only). However, I do have a separate problem with images not being accessible. I'll open a separate issue for that.

**Comment by oufmilo** [comment]
It's fixed now sorry for the inconvenient
