### ISSUE TITLE
Images do not load after upgrade.

### ISSUE THREAD

**Issue by panomaki** [YunoHost-Apps/bookwyrm_ynh#18]
After upgrading from 0.5.3 to 0.5.4 (testing), images that have been uploaded (e.g. logos, covers) do not load anymore. Placeholders (text) are shown instead. This is on a VPS.

Nginx error log shows:
[error] 412434#412434: *13198 open() "/home/yunohost.app/bookwyrm/images/logos/FILENAME" failed (2: No such file or directory), client: [IPADDDRESS], server: [SERVER], request: "GET /images/logos/FILENAME HTTP/2.0", 

I would guess there is a $-sign missing somewhere? The path should of course be /var/www/bookwyrm/images/logos/FILENAME.

**Comment by oufmilo** [comment]
i'm investigate ..

**Comment by oufmilo** [comment]
> After upgrading from 0.5.3 to 0.5.4 (testing), images that have been uploaded (e.g. logos, covers) do not load anymore. Placeholders (text) are shown instead. This is on a VPS.
> 
> Nginx error log shows: [error] 412434#412434: *13198 open() "/home/yunohost.app/bookwyrm/images/logos/FILENAME" failed (2: No such file or directory), client: [IPADDDRESS], server: [SERVER], request: "GET /images/logos/FILENAME HTTP/2.0",
> 
> I would guess there is a $-sign missing somewhere? The path should of course be /var/www/bookwyrm/images/logos/FILENAME.

Can you try this command please

`sudo yunohost app upgrade bookwyrm -u https://github.com/YunoHost-Apps/bookwyrm_ynh/tree/testing --debug`

And tell me if that's solved images loading

**Comment by panomaki** [comment]
> And tell me if that's solved images loading

Yes, that works. Thanks!
