### ISSUE TITLE
CSS not found

### ISSUE THREAD

**Issue by Fipaddict** [YunoHost-Apps/bookwyrm_ynh#25]
CSS not found after installing the bookwyrm_ynh application. 

I tested it on 2 different servers (local VM and VPS).
1. install from **webadmin** on dedicated subdomain https://mydedicated.domain.tld
2. generate admin code (with user root)
3. try to access to https://mydedicated.domain.tld
--> CSS not found
css link in html file : https://mydedicated.domain.tld/static/css/themes/bookwyrm-light.css
--> **404. not found**

4. try to specify a theme via `https://mydedicated.domain.tld/preferences/profile` : same issue.

on the server :
```bash 
$ sudo ls -l bookwyrm/static/css/themes/
total 8
-rwxr-xr-x 1 bookwyrm www-data 2611 Feb 22 21:32 bookwyrm-dark.scss
-rwxr-xr-x 1 bookwyrm www-data 1589 Feb 22 21:32 bookwyrm-light.scss
 $ sudo ls -l bookwyrm/bookwyrm/static/css/themes/
total 8
-rw-rw---- 1 bookwyrm www-data 2611 Jan 26 15:39 bookwyrm-dark.scss
-rw-rw-r-- 1 bookwyrm www-data 1589 Jan 26 15:39 bookwyrm-light.scss
```

``` bash
sudo yunohost --version
yunohost: 
  repo: stable
  version: 11.1.11.2
yunohost-admin: 
  repo: stable
  version: 11.1.6
moulinette: 
  repo: stable
  version: 11.1.4
ssowat: 
  repo: stable
  version: 11.1.4
 ```

**Comment by oufmilo** [comment]
#26 Fix
