### ISSUE TITLE
How to get the Admin Key? (docker-compose missing after installation)

### ISSUE THREAD

**Issue by brockhaus** [YunoHost-Apps/bookwyrm_ynh#30]
### Describe the bug

* unable to register an admin after installation as `./bw-dev admin_code` does not run because of missing `docker-compose`.

### Context

- Hardware: Raspberry Pie 4
- YunoHost version: 11.1.13 (stable)
- I have access to my server: *Through SSH and through the webadmin*

### Steps to reproduce

* install BookWyrm for yunohost
* Next you will be asked to register an admin account. You'll need an "admin key" you'll get calling `./bw-dev admin_code` on command line (so the interface says)
* I did that and get

    ```
root@home:/var/www/bookwyrm# ./bw-dev admin_code
+ case "$CMD" in
+ admin_code
+ runweb python manage.py admin_code
+ docker-compose run --rm web python manage.py admin_code
./bw-dev: line 32: docker-compose: command not found
    ```
### Expected behavior

* It looks like docker-compose is not installed but needed.

**Comment by brockhaus** [comment]
Found the solution from bookWyrm documentation:

Change to /var/www/bookwyrm and call

`sudo -u bookwyrm venv/bin/python3 manage.py admin_code`

This will work on raspi with yunohost.

**Comment by oufmilo** [comment]
Yes it's in the disclaimers information [here](https://github.com/YunoHost-Apps/bookwyrm_ynh#disclaimers--important-information)
