### ISSUE TITLE
Celery problems?

### ISSUE THREAD

**Issue by PrivacyDragon** [YunoHost-Apps/bookwyrm_ynh#46]
### What happened before the bug

12 days ago I tried to update Bookwyrm. I was shocked to find out that updating was not possible, as the backup would be around 3 GiB, while I only had 1 available. After some commands to figure out what size the database and the server files were, I found out that it was the book covers what made the application so huge. I set to work to copy all of them to a folder on my personal laptop, using scp, after which I deleted them on the server.
Now I was able to update Bookwyrm without problems, I thought.

### Description of the Bug

All seemed to be well. I only noticed that book covers were missing, but I already knew that.
Yesterday, it occurred to me that my timeline hadn't seen new posts since twelve days ago. What surprised me most was that my own posts did not show up. They did show on the page of the book they were written about, and I was able to find and boost them from my Mastodon account, but they did not appear in my own timeline. Furthermore, I did not get any notification that my posts were boosted.
I ssh'd my way into the server to take a look at the access log, where I saw that the mastodon instance had submitted a POST request to /inbox, which must mean that the notification of the boosting *was* delivered to my server.
I inspected the Celery query in the admin tab of my Bookwyrm instance. I posted and boosted another book quote, and refreshed the page. The number under 'inbox' had  increased.
So, methinks that Celery is not doing jobs. Restarting the 'bookwyrm-worker' service did not help. And it looks like Celery is not performing any job.

### Context

- Hardware: Hetzner VPS
- YunoHost version: 11.2.5
- I have access to my server: Through SSH & through the webadmin.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes 
  - If yes, please explain: See above.
- Using, or trying to install package version/branch:0.6.6\~ynh1
- 

### Steps to reproduce

1. Mess around with permissions, so that the admin user has permission to read the cover images.
2. From another server/device:
`scp -r admin@[SERVER_ADDRESS]:/var/www/bookwyrm/images/covers ~/BookwyrmCoversBackup`
3. On the server:
`sudo rm -rf /var/www/bookwyrm/images/covers`
4. Update

### Expected behavior

A bookwyrm instance that still works.

**Comment by PrivacyDragon** [comment]
Okay, it looks like I have kinda been able to fix the problems, but I think there are still problems to be solved.
I moved the image files back.

I started Flower, which I had previously already done without any results.
Now, once again, only the `high_priority`, `medium_priority`, `low_priority`, and `imports` queues were 'used'.
I had to manually tell the Celery worker to look in all the other queues.

**Comment by Thovi98** [comment]
>  Now, once again, only the high_priority, medium_priority, low_priority, and imports queues were 'used'.

Just looking at this issue, seems to be on purpose: cfr  https://github.com/YunoHost-Apps/bookwyrm_ynh/blob/a6d98fd63afe4c182e4061426ea94bb2fc75600f/conf/bookwyrm-worker.service#L12

>  I had to manually tell the Celery worker to look in all the other queues.

What command did you use?

**Comment by Thovi98** [comment]
> I started Flower

@PrivacyDragon may I ask you how you did?

**Comment by Thovi98** [comment]
I'm on it, thanks. It will be ready soon.

**Comment by PrivacyDragon** [comment]
> > I started Flower
> 
> @PrivacyDragon may I ask you how you did?

I ran `/var/www/bookwyrm/venv/bin/celery -A celerywyrm flower -A celerywyrm`



>> I had to manually tell the Celery worker to look in all the other queues.
>
> What command did you use?

In Flower there is an option to add queues to a worker. That's what I used. (You click on the worker, go to 'queues', and enter the name of the queue you want to add, after which you click 'Add Consumer'

**Comment by Thovi98** [comment]
> I ran /var/www/bookwyrm/venv/bin/celery -A celerywyrm flower -A celerywyrm

Thanks!
I have `You have incorrectly specified the following celery arguments after flower command: ['-A']. Please specify them after celery command instead following this template: celery [celery args] flower [flower args].`

or

```
Error: Invalid value for '-A' /  '--app':
Unable to load celery application.
The module celerywyrm was not found.
```
Do you have an idea?

Do you think it’s a good idea to incorporate flower in the package (once I know how to 😛)?

**Comment by PrivacyDragon** [comment]
I also get `You have incorrectly specified the following celery arguments after flower command: ['-A']. Please specify them after celery command instead following this template: celery [celery args] flower [flower args].`
However, when then heading to where Flower is, (I don't remember, I made a redirect application to be able to reach it), it works.
So I just ignore the comment. Possibly the command works with a bit less or something. But why try to change the command when you've found a way that works? (Unless you want to implement it, of course...)

The official Bookwyrm documentation seems to tell that Flower is enabled and ran automatically, so, maybe...

**Comment by Thovi98** [comment]
I didn’t get to make flower work (even by hand).
But latest testing https://github.com/YunoHost-Apps/bookwyrm_ynh/pull/51 must resolve your celery issue.
