### ISSUE TITLE
License warning?

### ISSUE THREAD

**Issue by agger-magenta** [YunoHost-Apps/bookwyrm_ynh#60]
Bookwyrm is published under the [Anti-capitalist Software License v. 1.4](https://github.com/bookwyrm-social/bookwyrm/blob/main/LICENSE.md).

As much as I sympathize with the idea of not supplying software to law enforcement or the military, this is not a free software license and maybe this package should contain some sort of warning about that? Normally I assume that software packaged in the Yunohost store is free software, i.e. under a roughly OSI-approved or FSF-approved license.

The current admin page for Bookwyrm in YNH also seems to indicate that Boowyrm is under the AGPL:

![image](https://github.com/YunoHost-Apps/bookwyrm_ynh/assets/4435559/f505b16c-3b20-4048-8353-49ad9176d4c6)

I wish, but it's not.

Should anything be done about this?

**Comment by OniriCorpe** [comment]
done in https://github.com/YunoHost/apps/pull/2051
