### ISSUE TITLE
A code generated via command line is required in the UI on first run

### ISSUE THREAD

**Issue by ewagoner** [YunoHost-Apps/bookwyrm_ynh#8]
### Describe the bug

After installing the app and running it for the first time, the app requests a GUID that is only available by running a CLI command. It needs to be available to the user somehow via the app's admin panel.

### Context

Information from https://docs.joinbookwyrm.com/install-prod-dockerless.html

```
Generate the admin code with 'sudo -u bookwyrm venv/bin/python3 manage.py admin_code', 
and copy the admin code to use when you create your admin account. You can get your code 
at any time by re-running that command. Here's an example output:
*******************************************
Use this code to create your admin account:
c6c35779-af3a-4091-b330-c026610920d6
*******************************************
```

This code is requested by the app when accessed for the first time to verify the admin user.

### Expected behavior

If the admin user can't be verified by direct db manipulation during the install (or some other end-run around this requirement), we need to generate this code and make it available to the user. I suppose this would need to be via the app's admin page in Yunohost administration, and well documented.

**Comment by oufmilo** [comment]
Maybe it's possible to send an email with the code in the yunohost admin account ?

**Comment by oufmilo** [comment]
[https://github.com/YunoHost-Apps/bookwyrm_ynh/commit/1cc39596447966b470956f3fae859e1c4f8d6174](Commit ✅)

**Comment by oufmilo** [comment]
#14 Readme.md
